# Generated by Django 5.1.5 on 2025-06-12 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rentals_options_remove_rentals_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentals',
            old_name='mini_description',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='rentals',
            name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='amenities',
            field=models.CharField(blank=True, max_length=1254, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rentals',
            name='bedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rentals',
            name='house_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='owner_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='owner_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentals',
            name='owner_post_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentals',
            name='sleeps',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentals.rentals'),
        ),
    ]
