# Generated by Django 5.1.5 on 2025-06-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rename_mini_description_rentals_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentals',
            old_name='house_name',
            new_name='name',
        ),
    ]
